export default {
  products: [
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
    {
      name: "Binoculars",
      category: "surveillance",
      image: "images/binoculars.png",
      price: 250,
      brand: "Binoculars Brand",
      rating: 4.6,
      numReviews: 10,
    },
    {
      name: "Night Cap",
      category: "surveillance",
      image: "images/night-cap.png",
      price: 350,
      brand: "Night Cap Brand",
      rating: 4.7,
      numReviews: 144,
    },
    {
      name: "Night Vision",
      category: "protection",
      image: "images/night-vision.png",
      price: 250,
      brand: "Night Vision Brand",
      rating: 4.9,
      numReviews: 19,
    },
    {
      name: "Security Camera",
      category: "surveillance",
      image: "images/security-camera.png",
      price: 150,
      brand: "Security Camera Brand",
      rating: 4.6,
      numReviews: 110,
    },
    {
      name: "Spotting Binoculars",
      category: "protection",
      image: "images/spotting.png",
      price: 210,
      brand: "Spotting Binoculars Brand",
      rating: 4.8,
      numReviews: 127,
    },
    {
      name: "Thermographic Binoculars",
      category: "protection",
      image: "images/thermographic.png",
      price: 325,
      brand: "Thermographic Binoculars Brand",
      rating: 4.8,
      numReviews: 90,
    },
  ],
};
